package TestScript;

import java.util.List;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import Pages.AddGroup;
import Utiles.Browser;
import Utiles.ExtentReportManager;
import Utiles.PropertyReader;
import Validation.Validation_AddGroup;

public class AddGroupTest {
	WebDriver driver;
	AddGroup log;
	@BeforeMethod
	public void Setup() throws Exception
	{
		List<String>info=PropertyReader.getdata("Browser", 1);
		String broswername=info.get(0),drivername=info.get(1),url=info.get(2);
		driver=Browser.Launching_Browser(broswername, drivername);
		driver=Browser.Open_Url(url);
	}

	@AfterMethod
	public void closebroswer()
	{
		driver.close();
		ExtentReportManager.stopReport();
	}
  @Test(priority=1)
  public void Login() throws Exception {
		ExtentReportManager.startTest("Login", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(1000);
		log.isdisplayErrormsg();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_AddGroup.Valid_Login);
  }
  @Test(priority=2)
  public void Click_AddButton() throws Exception {
		ExtentReportManager.startTest("Click_AddButton", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		log.isdisplayErrormsg1();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logPass(Validation_AddGroup.Click_Add);
  }
  @Test(priority=3)
  public void Click_Submit_In_AddGroup() throws Exception {
		ExtentReportManager.startTest("Click_Submit_In_AddGroup", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		log.Click_On_Create_Btn();
		Thread.sleep(1000);
		log.isdisplayErrormsg2();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : ");
		ExtentReportManager.logInfo("Group Description : ");
		ExtentReportManager.logPass(Validation_AddGroup.Click_Create);
  }
  @Test(priority=4)
  public void Enter_Only_GroupName() throws Exception {
		ExtentReportManager.startTest("Enter_Only_GroupName", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 1);
		String groupname=info1.get(0);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		Thread.sleep(1000);
		log.Click_On_Create_Btn();
		Thread.sleep(1000);
		log.isdisplayErrormsg3();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Abc");
		ExtentReportManager.logInfo("Group Description : ");
		ExtentReportManager.logPass(Validation_AddGroup.Enter_Only_GroupName);
  }
  @Test(priority=5)
  public void Enter_GroupName_1character() throws Exception {
		ExtentReportManager.startTest("Enter_GroupName_1character", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 2);
		String groupname=info1.get(0);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		Thread.sleep(1000);
		log.Click_On_Create_Btn();
		Thread.sleep(1000);
		log.isdisplayErrormsg4();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : a");
		ExtentReportManager.logInfo("Group Description : ");
		ExtentReportManager.logPass(Validation_AddGroup.Enter_GroupName_1charater);
  }
  @Test(priority=6)
  public void Enter_Only_Description() throws Exception {
		ExtentReportManager.startTest("Enter_Only_Description", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 3);
		//String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		//log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		Thread.sleep(1000);
		log.Click_On_Create_Btn();
		Thread.sleep(1000);
		log.isdisplayErrormsg5();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : ");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on create button");
		ExtentReportManager.logPass(Validation_AddGroup.Enter_Only_Description);
  }
  @Test(priority=7)
  public void Enter_GroupName_Description() throws Exception {
		ExtentReportManager.startTest("Enter_GroupName_Description", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 4);
		String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		Thread.sleep(1000);
		log.Click_On_Create_Btn();
		Thread.sleep(1000);
		log.isdisplayErrormsg6();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : abc");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on create button");
		ExtentReportManager.logPass(Validation_AddGroup.Enter_GroupName_Description);
  }
  @Test(priority=8)
  public void Valid_Search_User() throws Exception {
		ExtentReportManager.startTest("Valid_Search_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 4);
		String groupname=info1.get(0);
		String description=info1.get(1);
		String search=info1.get(2);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		Thread.sleep(1000);
		log.Search_User(search);
		log.Validate_valid_Search();
		Thread.sleep(1000);
		log.Validate_Add_User1();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Abcd");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on search");
		ExtentReportManager.logPass(Validation_AddGroup.Search_User);
		ExtentReportManager.logInfo("Enter user name: abcd");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
  }
  @Test(priority=9)
  public void InValid_Search_User() throws Exception {
		ExtentReportManager.startTest("InValid_Search_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 5);
		String groupname=info1.get(0);
		String description=info1.get(1);
		String search=info1.get(2);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		Thread.sleep(1000);
		log.Validate_valid_Search();
		log.Invalid_Search_User(search);
		log.Validate_Invalid_Search();
		Thread.sleep(1000);
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on search");
		ExtentReportManager.logPass(Validation_AddGroup.Search_User);
		ExtentReportManager.logInfo("Enter User name : fdsfafdg");
		ExtentReportManager.logPass(Validation_AddGroup.Invalid_Search_User);
  }
  @Test(priority=10)
  public void Close_Search_User() throws Exception {
		ExtentReportManager.startTest("Close_Search_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 6);
		String groupname=info1.get(0);
		String description=info1.get(1);
		String search=info1.get(2);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		Thread.sleep(1000);
		log.Search_User(search);
		log.Close_Search_User();
		Thread.sleep(1000);
		log.Validate_Add_User1();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on search");
		ExtentReportManager.logPass(Validation_AddGroup.Search_User);
		ExtentReportManager.logInfo("Enter user name : abcd");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
		ExtentReportManager.logInfo("Click on close button in search");
		ExtentReportManager.logPass(Validation_AddGroup.Close_Search_User);
  }
  @Test(priority=11)
  public void Add_Users() throws Exception {
		ExtentReportManager.startTest("Add_Users", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 7);
		String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		log.Add_User1();
		Thread.sleep(2000);
		log.Add_User2();
		Thread.sleep(2000);
		log.Validate_Add_User1();
		log.Validate_Add_User2();
		log.Selected_Count();
		Thread.sleep(2000);
		log.Click_On_Create_Btn();
		Thread.sleep(1000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on User1");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
		ExtentReportManager.logInfo("Click on user2");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser2);
		ExtentReportManager.logPass(Validation_AddGroup.Selected_Count);
		ExtentReportManager.logInfo("Click on create button");
		ExtentReportManager.logPass(Validation_AddGroup.Enter_GroupName_Description);
  }
  @Test(priority=12)
  public void Add_Users_Make_Admin() throws Exception {
		ExtentReportManager.startTest("Add_Users_Make_Admin", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 7);
		String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		log.Add_User1();
		Thread.sleep(2000);
		log.Add_User2();
		Thread.sleep(2000);
		log.Validate_Add_User1();
		log.Validate_Add_User2();
		log.Selected_Count();
		Thread.sleep(2000);
		log.Make_Admin();
		log.Validate_Make_Admin();
		Thread.sleep(2000);
		log.Click_On_Create_Btn();
		Thread.sleep(1000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on User1");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
		ExtentReportManager.logInfo("Click on user2");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser2);
		ExtentReportManager.logPass(Validation_AddGroup.Selected_Count);
		ExtentReportManager.logInfo("Click on Admin for user1");
		ExtentReportManager.logPass(Validation_AddGroup.Make_Admin);
		ExtentReportManager.logInfo("Click on create");
		ExtentReportManager.logPass(Validation_AddGroup.Enter_GroupName_Description);
  }
  @Test(priority=13)
  public void Add_Users_Make_Moderator() throws Exception {
		ExtentReportManager.startTest("Add_Users_Make_Moderator", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 7);
		String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		log.Add_User1();
		Thread.sleep(2000);
		log.Add_User2();
		Thread.sleep(2000);
		log.Validate_Add_User1();
		log.Validate_Add_User2();
		log.Selected_Count();
		Thread.sleep(2000);
		log.Make_Moderator();
		log.Validate_Make_Moderator();
		Thread.sleep(2000);
		log.Click_On_Create_Btn();
		Thread.sleep(1000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on User1");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
		ExtentReportManager.logInfo("Click on user2");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser2);
		ExtentReportManager.logPass(Validation_AddGroup.Selected_Count);
		ExtentReportManager.logInfo("Click on Moderator for user1");
		ExtentReportManager.logPass(Validation_AddGroup.Make_Moderator);
		ExtentReportManager.logInfo("Click on create");
		ExtentReportManager.logPass(Validation_AddGroup.Enter_GroupName_Description);
  }
  @Test(priority=14)
  public void Add_Remove_Users() throws Exception {
		ExtentReportManager.startTest("Add_Remove_Users", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 8);
		String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		log.Add_User1();
		Thread.sleep(2000);
		log.Add_User2();
		Thread.sleep(2000);
		log.Validate_Add_User1();
		log.Validate_Add_User2();
		log.Selected_Count();
		Thread.sleep(2000);
		log.Remove_User();
		log.Selected_Count1();
		//log.Click_On_Create_Btn();
		Thread.sleep(1000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on User1");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
		ExtentReportManager.logInfo("Click on user2");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser2);
		ExtentReportManager.logPass(Validation_AddGroup.Selected_Count);
		ExtentReportManager.logInfo("Click on Remove for user1");
		ExtentReportManager.logPass(Validation_AddGroup.Remove_User);
		ExtentReportManager.logPass(Validation_AddGroup.Selected_Count1);
  }
  @Test(priority=15)
  public void Close_AddGroup() throws Exception {
		ExtentReportManager.startTest("Close_AddGroup", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 9);
		String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		log.Add_User1();
		Thread.sleep(2000);
		log.Add_User2();
		Thread.sleep(2000);
		log.Validate_Add_User1();
		log.Validate_Add_User2();
		log.Selected_Count();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on User1");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
		ExtentReportManager.logInfo("Click on user2");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser2);
		ExtentReportManager.logPass(Validation_AddGroup.Selected_Count);
		ExtentReportManager.logInfo("Click on Close button of group");
		
		ExtentReportManager.logPass(Validation_AddGroup.Close_AddGroup);
		log.Validate_Close_Group();
		log.Close_AddGroup();
		Thread.sleep(1000);
  }
  @Test(priority=16)
  public void Create_Group() throws Exception {
		ExtentReportManager.startTest("Create_Group", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 9);
		String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		log.Add_User1();
		Thread.sleep(2000);
		log.Add_User2();
		Thread.sleep(2000);
		log.Validate_Add_User1();
		log.Validate_Add_User2();
		log.Selected_Count();
		Thread.sleep(1000);
		log.Click_On_Create_Btn();
		Thread.sleep(1000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on User1");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
		ExtentReportManager.logInfo("Click on user2");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser2);
		ExtentReportManager.logPass(Validation_AddGroup.Selected_Count);
		ExtentReportManager.logInfo("Click on create button");
		ExtentReportManager.logPass(Validation_AddGroup.Enter_GroupName_Description);
  }
  @Test(priority=17)
  public void Click_Checkbox_Airtime_Group() throws Exception {
		ExtentReportManager.startTest("Click_Checkbox_Airtime_Group", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 9);
		String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		log.Add_User1();
		Thread.sleep(2000);
		log.Add_User2();
		Thread.sleep(2000);
		log.Validate_Add_User1();
		log.Validate_Add_User2();
		log.Selected_Count();
		Thread.sleep(2000);
		log.Create_Airtime_Group();
		Thread.sleep(1000);
		log.Airtime_Group_i_Symbol();
		Thread.sleep(1000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on User1");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
		ExtentReportManager.logInfo("Click on user2");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser2);
		ExtentReportManager.logPass(Validation_AddGroup.Selected_Count);
		ExtentReportManager.logInfo("Click on checkbox of Airtime Group");
		ExtentReportManager.logInfo("Click on i symbol of Airtime group");
		ExtentReportManager.logPass(Validation_AddGroup.i_symbol);
  }
  @Test(priority=18)
  public void Create_Airtime_Group() throws Exception {
		ExtentReportManager.startTest("Create_Airtime_Group", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new AddGroup(driver);
		List<String> info= PropertyReader.getdata("AddGrouppage", 1);
		String Email=info.get(0);
		String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.TRoop_Login(Email, Password);
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(3000);
		log.Click_On_Add_Btn();
		Thread.sleep(2000);
		List<String> info1= PropertyReader.getData("AddGrouppage", 9);
		String groupname=info1.get(0);
		String description=info1.get(1);
		Thread.sleep(2000);
		log.Enter_GroupName(groupname);
		log.Enter_Description(description);
		log.Description_Count();
		log.Add_User1();
		Thread.sleep(2000);
		log.Add_User2();
		Thread.sleep(2000);
		log.Validate_Add_User1();
		log.Validate_Add_User2();
		log.Selected_Count();
		Thread.sleep(2000);
		log.Create_Airtime_Group();
		Thread.sleep(1000);
		log.Airtime_Group_i_Symbol();
		Thread.sleep(1000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logInfo("Click on Add button");
		ExtentReportManager.logInfo("Group Name : Group creation");
		ExtentReportManager.logInfo("Group Description : Troop");
		ExtentReportManager.logPass(Validation_AddGroup.Description_Count);
		ExtentReportManager.logInfo("Click on User1");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser1);
		ExtentReportManager.logInfo("Click on user2");
		ExtentReportManager.logPass(Validation_AddGroup.Validate_AddUser2);
		ExtentReportManager.logPass(Validation_AddGroup.Selected_Count);
		ExtentReportManager.logInfo("Click on checkbox of Airtime Group");
		ExtentReportManager.logInfo("Click on i symbol of Airtime group");
		ExtentReportManager.logPass(Validation_AddGroup.i_symbol);
		ExtentReportManager.logInfo("Click on create button");
		ExtentReportManager.logPass(Validation_AddGroup.Enter_GroupName_Description);
  }
}
