package TestScript;

import java.util.List;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import Pages.Bridgecallpage;
import Utiles.Browser;
import Utiles.ExtentReportManager;
import Utiles.PropertyReader;
import Validation.Validation_BridgeCall;

public class BridgecallTest {
	WebDriver driver;
	Bridgecallpage log;
	@BeforeMethod
	public void Setup() throws Exception 
	{
		List<String>info=PropertyReader.getdata("Browser", 1);
		String broswername=info.get(0),drivername=info.get(1),url=info.get(2);
		driver=Browser.Launching_Browser(broswername, drivername);
		driver=Browser.Open_Url(url);
	}

	@AfterMethod
	public void closebroswer()
	{
		driver.close();
		ExtentReportManager.stopReport();
	}
	@Test(priority=1)
	public void Login() throws Exception {
		ExtentReportManager.startTest("Login", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
	}
	@Test(priority=2)
	public void Click_On_Bridge_Call_In_Utilites() throws Exception {
		ExtentReportManager.startTest("Click_On_Bridge_Call_In_Utilites", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
	}
	@Test(priority=3)
	public void Click_On_Create_New() throws Exception {
		ExtentReportManager.startTest("Click_On_Create_New", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(2000);
		log.Validate_Create_New();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
	}
	@Test(priority=4)
	public void Click_On_Invite_Without_Entering_Title() throws Exception {
		ExtentReportManager.startTest("Click_On_Invite_Without_Entering_Title", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Enter_Title();
		Thread.sleep(1000);
		log.Click_On_Invite();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Don't enter title & Click on invite");
		ExtentReportManager.logPass(Validation_BridgeCall.Enter_Title);
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Invite);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Toast_Msg);
	}
	@Test(priority=5)
	public void Click_On_Invite_With_Entering_Only_Title() throws Exception {
		ExtentReportManager.startTest("Click_On_Invite_With_Entering_Only_Title", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Enter_Title();
		log.Enter_Title("test");
		Thread.sleep(1000);
		log.Click_On_Invite();
		Thread.sleep(1000);
		log.Validate_Toast_Msg1();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Enter title & Click on invite");
		ExtentReportManager.logPass(Validation_BridgeCall.Enter_Title);
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Invite);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Toast_Msg1);
	}
	@Test(priority=6)
	public void Click_On_Invite_With_Selecting_Only_User() throws Exception {
		ExtentReportManager.startTest("Click_On_Invite_With_Selecting_Only_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Click_On_Invite();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Select user & Click on invite");
		ExtentReportManager.logPass(Validation_BridgeCall.Select_User);
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Invite);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Toast_Msg2);
	}
	@Test(priority=7)
	public void Search_Valid_User_In_Members() throws Exception {
		ExtentReportManager.startTest("Search_Valid_User_In_Members", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Members();
		log.Members_Count();
		log.Search_Members("browser");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Enter valid username in search & Validate the username");
		ExtentReportManager.logPass(Validation_BridgeCall.Members);
		ExtentReportManager.logPass(Validation_BridgeCall.Members_Count);
		ExtentReportManager.logPass(Validation_BridgeCall.Search_Members);
		ExtentReportManager.logPass(Validation_BridgeCall.Select_User);
	}
	@Test(priority=8)
	public void Search_Invalid_User_In_Members() throws Exception {
		ExtentReportManager.startTest("Search_Invalid_User_In_Members", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Members();
		log.Members_Count();
		log.Search_Members("sdfsd");
		Thread.sleep(1000);
		log.No_Result();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Enter valid username in search & Validate page");
		ExtentReportManager.logPass(Validation_BridgeCall.Members);
		ExtentReportManager.logPass(Validation_BridgeCall.Members_Count);
		ExtentReportManager.logPass(Validation_BridgeCall.Search_Members);
		ExtentReportManager.logPass(Validation_BridgeCall.No_Result);
	}
	@Test(priority=9)
	public void Search_Valid_User_In_Selected_Members() throws Exception {
		ExtentReportManager.startTest("Search_Valid_User_In_Selected_Members", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Members();
		log.Select_User();
		Thread.sleep(1000);
		log.Selected_Members();
		log.Selected_Members_Count();
		log.Search_Selected_Members("browser");
		Thread.sleep(1000);
		log.Select_User1();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Select the user in members");
		ExtentReportManager.logPass(Validation_BridgeCall.Members);
		ExtentReportManager.logPass(Validation_BridgeCall.Select_User);
		ExtentReportManager.logInfo("Search the selected user in selected members & Validate the user");
		ExtentReportManager.logPass(Validation_BridgeCall.Selected_Members);
		ExtentReportManager.logPass(Validation_BridgeCall.Selected_Members_Count);
		ExtentReportManager.logPass(Validation_BridgeCall.Search_Selected_Members);
		ExtentReportManager.logPass(Validation_BridgeCall.Select_User1);
	}
	@Test(priority=10)
	public void Search_Invalid_User_In_Selected_Members() throws Exception {
		ExtentReportManager.startTest("Search_Invalid_User_In_Selected_Members", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Members();
		log.Select_User();
		Thread.sleep(1000);
		log.Selected_Members();
		log.Selected_Members_Count();
		log.Search_Selected_Members("fsdafdf");
		Thread.sleep(1000);
		log.No_Result();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Select the user in members");
		ExtentReportManager.logPass(Validation_BridgeCall.Members);
		ExtentReportManager.logPass(Validation_BridgeCall.Select_User);
		ExtentReportManager.logInfo("Search the invalid username in selected members & Validate it");
		ExtentReportManager.logPass(Validation_BridgeCall.Selected_Members);
		ExtentReportManager.logPass(Validation_BridgeCall.Selected_Members_Count);
		ExtentReportManager.logPass(Validation_BridgeCall.Search_Selected_Members);
		ExtentReportManager.logPass(Validation_BridgeCall.No_Result);
	}
	@Test(priority=11)
	public void Deselect_The_Enable_Waiting_Room() throws Exception {
		ExtentReportManager.startTest("Deselect_The_Enable_Waiting_Room", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Enable_Waiting_Room();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Deselect the enable waiting room");
		ExtentReportManager.logPass(Validation_BridgeCall.Enable_Waiting_Room);
	}
	@Test(priority=12)
	public void Deselect_The_Allow_Others_To_Invite() throws Exception {
		ExtentReportManager.startTest("Deselect_The_Allow_Others_To_Invite", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Allow_Others_To_Invite();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Deselect the allow others to invite");
		ExtentReportManager.logPass(Validation_BridgeCall.Allow_Others_To_Invite);
	}
	@Test(priority=13)
	public void Click_On_Invite_By_Entering_Details() throws Exception {
		ExtentReportManager.startTest("Click_On_Invite_By_Entering_Details", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Validate_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Click_On_Create_New();
		Thread.sleep(1000);
		log.Validate_Create_New();
		Thread.sleep(1000);
		log.Enter_Title();
		log.Enter_Title("test");
		Thread.sleep(1000);
		log.Select_User();
		log.Selected_User();
		Thread.sleep(1000);
		log.Click_On_Invite();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Click on Create new");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Create_New);
		ExtentReportManager.logInfo("Validate Create new page");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Create_New);
		ExtentReportManager.logInfo("Enter title : test");
		ExtentReportManager.logPass(Validation_BridgeCall.Enter_Title);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_BridgeCall.Select_User);
		ExtentReportManager.logInfo("Validate the Selected user");
		ExtentReportManager.logPass(Validation_BridgeCall.Selected_User);
		ExtentReportManager.logInfo("Click on invite");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Invite);
	}
	@Test(priority=14)
	public void Validate_The_Call_In_Bridge_Call() throws Exception {
		ExtentReportManager.startTest("Validate_The_Call_In_Bridge_Call", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Bridgecallpage(driver);
		List<String> info= PropertyReader.getdata("bridgecall", 2);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(2000);
		log.Click_On_Utilities();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Bridge_Call_Tab();
		Thread.sleep(1000);
		log.Bridge_Call_List();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_BridgeCall.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilites tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Utilities);
		ExtentReportManager.logInfo("Click on Bridge call tab");
		ExtentReportManager.logPass(Validation_BridgeCall.Click_On_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate Bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Validate_Bridge_Call_Tab);
		ExtentReportManager.logInfo("Validate the running bridge call");
		ExtentReportManager.logPass(Validation_BridgeCall.Bridge_Call_List);
	}
}
