package TestScript;

import java.util.List;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import Pages.Cattlecallpage;
import Utiles.Browser;
import Utiles.ExtentReportManager;
import Utiles.PropertyReader;
import Validation.Validation_CattleCall;

public class CattlecallTest {
	WebDriver driver;
	Cattlecallpage log;
	@BeforeMethod
	public void Setup() throws Exception 
	{
		List<String>info=PropertyReader.getdata("Browser", 1);
		String broswername=info.get(0),drivername=info.get(1),url=info.get(2);
		driver=Browser.Launching_Browser(broswername, drivername);
		driver=Browser.Open_Url(url);
	}

	@AfterMethod
	public void closebroswer()
	{
		driver.close();
		ExtentReportManager.stopReport();
	}
	@Test(priority=1)
	public void Login() throws Exception {
		ExtentReportManager.startTest("Login", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
	}
	@Test(priority=2)
	public void Click_On_Cattle_Call() throws Exception {
		ExtentReportManager.startTest("Click_On_Cattle_Call", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
	}
	@Test(priority=3)
	public void Validate_Cattle_Call() throws Exception {
		ExtentReportManager.startTest("Validate_Cattle_Call", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
	}
	@Test(priority=4)
	public void Click_On_Now_Button() throws Exception {
		ExtentReportManager.startTest("Click_On_Now_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Now_Button();
		log.Wrapper();
		Thread.sleep(2000);		
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on now button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Now_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper);
	}
	@Test(priority=5)
	public void Validate_Now_Button() throws Exception {
		ExtentReportManager.startTest("Validate_Now_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Now_Button();
		log.Wrapper();
		Thread.sleep(2000);	
		log.Validate_Now();
		Thread.sleep(1000);
		log.Selected_Members();
		log.User_Count();
		log.Button();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on now button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Now_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper);
		ExtentReportManager.logInfo("Validate now button");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Now);
		ExtentReportManager.logPass(Validation_CattleCall.Selected_Members);
		ExtentReportManager.logPass(Validation_CattleCall.User_Count);
		ExtentReportManager.logPass(Validation_CattleCall.Button);
	}
	@Test(priority=6)
	public void Click_On_Cancel_Button_Without_Selecting_Users() throws Exception {
		ExtentReportManager.startTest("Click_On_Cancel_Button_Without_Selecting_Users", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Now_Button();
		log.Wrapper();
		Thread.sleep(1000);	
		log.Validate_Now();
		Thread.sleep(1000);
		log.Selected_Members();
		log.User_Count();
		Thread.sleep(1000);
		log.Click_On_Cancel();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on now button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Now_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper);
		ExtentReportManager.logInfo("Validate now button");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Now);
		ExtentReportManager.logPass(Validation_CattleCall.Selected_Members);
		ExtentReportManager.logPass(Validation_CattleCall.User_Count);
		ExtentReportManager.logInfo("Click on cancel button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cancel);
	}
	@Test(priority=7)
	public void Click_On_Invite_Button_Without_Selecting_Users() throws Exception {
		ExtentReportManager.startTest("Click_On_Invite_Button_Without_Selecting_Users", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Now_Button();
		log.Wrapper();
		Thread.sleep(1000);	
		log.Validate_Now();
		Thread.sleep(1000);
		log.Selected_Members();
		log.User_Count();
		Thread.sleep(1000);
		log.Click_On_Invite();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on now button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Now_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper);
		ExtentReportManager.logInfo("Validate now button");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Now);
		ExtentReportManager.logPass(Validation_CattleCall.Selected_Members);
		ExtentReportManager.logPass(Validation_CattleCall.User_Count);
		ExtentReportManager.logInfo("Click on invite button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Invite);
	}
	@Test(priority=8)
	public void Search_User() throws Exception {
		ExtentReportManager.startTest("Search_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Now_Button();
		log.Wrapper();
		Thread.sleep(1000);	
		log.Validate_Now();
		Thread.sleep(1000);
		log.Selected_Members();
		log.User_Count();
		Thread.sleep(1000);
		log.Search_User("amit");
		log.Select_User();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on now button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Now_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper);
		ExtentReportManager.logInfo("Validate now button");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Now);
		ExtentReportManager.logPass(Validation_CattleCall.Selected_Members);
		ExtentReportManager.logPass(Validation_CattleCall.User_Count);
		ExtentReportManager.logInfo("Click on search & enter username");
		ExtentReportManager.logPass(Validation_CattleCall.Search_User);
		ExtentReportManager.logInfo("Validatethe entered username");
		ExtentReportManager.logPass(Validation_CattleCall.Select_User);
	}
	@Test(priority=9)
	public void Enter_Invalid_Email_In_External_User() throws Exception {
		ExtentReportManager.startTest("Enter_Invalid_Email_In_External_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Now_Button();
		log.Wrapper();
		Thread.sleep(1000);	
		log.Validate_Now();
		Thread.sleep(1000);
		log.Selected_Members();
		log.User_Count();
		Thread.sleep(1000);
		log.Click_On_External_Tab();
		Thread.sleep(1000);
		log.Validate_External_Text();
		log.External_History();
		Thread.sleep(1000);
		log.Enter_Email("email");
		Thread.sleep(1000);
		log.Enter_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(1000);
		log.User_Count2();
		Thread.sleep(1000);
		Thread.sleep(1000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on now button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Now_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper);
		ExtentReportManager.logInfo("Validate now button");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Now);
		ExtentReportManager.logPass(Validation_CattleCall.Selected_Members);
		ExtentReportManager.logPass(Validation_CattleCall.User_Count);
		ExtentReportManager.logInfo("Click on external tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_External_Tab);
		ExtentReportManager.logInfo("Validate the external tab");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_External_Text);
		ExtentReportManager.logPass(Validation_CattleCall.External_History);
		ExtentReportManager.logInfo("Enter invalid email");
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Email);
		ExtentReportManager.logInfo("Click on enter button");
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg2);
		ExtentReportManager.logInfo("Validate the count of external & internal");
		ExtentReportManager.logPass(Validation_CattleCall.User_Count2);
	}
	@Test(priority=10)
	public void Click_On_Invite_Button_With_Selecting_Users_External_User() throws Exception {
		ExtentReportManager.startTest("Click_On_Invite_Button_With_Selecting_Users_External_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Now_Button();
		log.Wrapper();
		Thread.sleep(1000);	
		log.Validate_Now();
		Thread.sleep(1000);
		log.Selected_Members();
		log.User_Count();
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Selected_Members1();
		Thread.sleep(1000);
		log.Click_On_External_Tab();
		Thread.sleep(1000);
		log.Validate_External_Text();
		log.External_History();
		Thread.sleep(1000);
		log.Enter_Email("dummy@tm.com");
		Thread.sleep(1000);
		log.Enter_Button();
		Thread.sleep(1000);
		log.Selected_External_User();
		log.User_Count1();
		Thread.sleep(1000);
		log.Click_On_Invite();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on now button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Now_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper);
		ExtentReportManager.logInfo("Validate now button");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Now);
		ExtentReportManager.logPass(Validation_CattleCall.Selected_Members);
		ExtentReportManager.logPass(Validation_CattleCall.User_Count);
		ExtentReportManager.logInfo("Select the user & Validate the user");
		ExtentReportManager.logPass(Validation_CattleCall.Select_User);
		ExtentReportManager.logPass(Validation_CattleCall.Selected_Members1);
		ExtentReportManager.logInfo("Click on external tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_External_Tab);
		ExtentReportManager.logInfo("Validate the external tab");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_External_Text);
		ExtentReportManager.logPass(Validation_CattleCall.External_History);
		ExtentReportManager.logInfo("Enter email");
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Email);
		ExtentReportManager.logInfo("Click on enter button");
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Button);
		ExtentReportManager.logInfo("Validate the entered external user");
		ExtentReportManager.logPass(Validation_CattleCall.Selected_External_User);
		ExtentReportManager.logInfo("Validate the count of external & internal");
		ExtentReportManager.logPass(Validation_CattleCall.User_Count1);
		ExtentReportManager.logInfo("Click on invite button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Invite);
	}
	@Test(priority=11)
	public void Edit_The_Cattle_Call_Meeting() throws Exception {
		ExtentReportManager.startTest("Edit_The_Cattle_Call_Meeting", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 2);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Today_Meeting2();
		log.Edit_Meeting();
		Thread.sleep(500);
		log.Validate_Toast_Msg1();
		Thread.sleep(2000);
		log.Wrapper2();
		Thread.sleep(2000);	
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Validate the today's meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting2);
		ExtentReportManager.logInfo("Click on edit button for meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Edit_Meeting);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Now);
		ExtentReportManager.logInfo("Validate scheduled meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper2);
	}
	@Test(priority=12)
	public void Edit_The_Cattle_Call_Meeting_With_Schedule_Button() throws Exception {
		ExtentReportManager.startTest("Edit_The_Cattle_Call_Meeting_With_Schedule_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 2);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Today_Meeting2();
		log.Edit_Meeting();
		Thread.sleep(500);
		log.Validate_Toast_Msg1();
		Thread.sleep(2000);
		log.Wrapper2();
		log.Schedule_Meeting();
		Thread.sleep(1000);
		log.Validate_Toast_Msg4();
		Thread.sleep(2000);	
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Validate the today's meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting2);
		ExtentReportManager.logInfo("Click on edit button for meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Edit_Meeting);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg1);
		ExtentReportManager.logInfo("Validate scheduled meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper2);
		ExtentReportManager.logInfo("Click on schedule button");
		ExtentReportManager.logPass(Validation_CattleCall.Schedule_Meeting);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg4);
	}
	@Test(priority=13)
	public void Edit_The_Cattle_Call_Meeting_With_Cancel_Button() throws Exception {
		ExtentReportManager.startTest("Edit_The_Cattle_Call_Meeting_With_Cancel_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 2);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Today_Meeting2();
		log.Edit_Meeting();
		Thread.sleep(500);
		log.Validate_Toast_Msg1();
		Thread.sleep(2000);
		log.Wrapper2();
		log.Cancel_Meeting();
		Thread.sleep(2000);	
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Validate the today's meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting2);
		ExtentReportManager.logInfo("Click on edit button for meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Edit_Meeting);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg1);
		ExtentReportManager.logInfo("Validate scheduled meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper2);
		ExtentReportManager.logInfo("Click on cancel button");
		ExtentReportManager.logPass(Validation_CattleCall.Cancel_Meeting);
	}
	@Test(priority=14)
	public void Edit_The_Cattle_Call_Meeting_With_Back_Button() throws Exception {
		ExtentReportManager.startTest("Edit_The_Cattle_Call_Meeting_With_Back_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 2);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Today_Meeting2();
		log.Edit_Meeting();
		Thread.sleep(500);
		log.Validate_Toast_Msg1();
		Thread.sleep(2000);
		log.Wrapper2();
		log.Back_Meeting();
		Thread.sleep(2000);	
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Validate the today's meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting2);
		ExtentReportManager.logInfo("Click on edit button for meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Edit_Meeting);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg1);
		ExtentReportManager.logInfo("Validate scheduled meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper2);
		ExtentReportManager.logInfo("Click on back button");
		ExtentReportManager.logPass(Validation_CattleCall.Back_Meeting);
	}
	@Test(priority=15)
	public void Delete_The_Cattle_Call_Meeting_With_No_Button() throws Exception {
		ExtentReportManager.startTest("Delete_The_Cattle_Call_Meeting_With_No_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 3);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Today_Meeting3();
		log.Delete_Meeting();
		Thread.sleep(500);
		log.Delete_Confirmation();
		Thread.sleep(2000);
		log.Delete_No_Button();
		Thread.sleep(2000);	
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Validate the today's meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting3);
		ExtentReportManager.logInfo("Click on delete button for meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Delete_Meeting);
		ExtentReportManager.logInfo("Validate the confirmation msg");
		ExtentReportManager.logPass(Validation_CattleCall.Delete_Confirmation);
		ExtentReportManager.logInfo("Click on No button");
		ExtentReportManager.logPass(Validation_CattleCall.Delete_No_Button);
	}
	@Test(priority=16)
	public void Delete_The_Cattle_Call_Meeting_With_Close_Button() throws Exception {
		ExtentReportManager.startTest("Delete_The_Cattle_Call_Meeting_With_Close_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 3);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Today_Meeting3();
		log.Delete_Meeting();
		Thread.sleep(500);
		log.Delete_Confirmation();
		Thread.sleep(2000);
		log.Delete_Close_Button();
		Thread.sleep(2000);	
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Validate the today's meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting3);
		ExtentReportManager.logInfo("Click on delete button for meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Delete_Meeting);
		ExtentReportManager.logInfo("Validate the confirmation msg");
		ExtentReportManager.logPass(Validation_CattleCall.Delete_Confirmation);
		ExtentReportManager.logInfo("Click on close button for popup msg");
		ExtentReportManager.logPass(Validation_CattleCall.Delete_Close_Button);
	}
	@Test(priority=17)
	public void Delete_The_Cattle_Call_Meeting_With_Yes_Button() throws Exception {
		ExtentReportManager.startTest("Delete_The_Cattle_Call_Meeting_With_Yes_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 3);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Today_Meeting3();
		log.Delete_Meeting();
		Thread.sleep(500);
		log.Delete_Confirmation();
		Thread.sleep(2000);
		log.Delete_Yes_Button();
		Thread.sleep(2000);	
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Validate the today's meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting3);
		ExtentReportManager.logInfo("Click on delete button for meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Delete_Meeting);
		ExtentReportManager.logInfo("Validate the confirmation msg");
		ExtentReportManager.logPass(Validation_CattleCall.Delete_Confirmation);
		ExtentReportManager.logInfo("Click on Yes button");
		ExtentReportManager.logPass(Validation_CattleCall.Delete_Yes_Button);
	}
	@Test(priority=18)
	public void Click_On_Later_Button() throws Exception {
		ExtentReportManager.startTest("Click_On_Later_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Later_Button();
		log.Wrapper1();
		Thread.sleep(2000);		
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on later button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Later_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper1);
	}
	@Test(priority=19)
	public void Schedule_The_Meeting_Without_Entering_Any_Data() throws Exception {
		ExtentReportManager.startTest("Schedule_The_Meeting_Without_Entering_Any_Data", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Later_Button();
		log.Wrapper1();
		Thread.sleep(1000);
		log.Schedule_Meeting();
		Thread.sleep(1000);	
		log.Validate_Toast_Msg5();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on later button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Later_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper1);
		ExtentReportManager.logInfo("Click on schedule button");
		ExtentReportManager.logPass(Validation_CattleCall.Schedule_Meeting);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg5);
	}
	@Test(priority=20)
	public void Schedule_The_Meeting_With_Entering_Only_Title_Name() throws Exception {
		ExtentReportManager.startTest("Schedule_The_Meeting_With_Entering_Only_Title_Name", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Later_Button();
		log.Wrapper1();
		Thread.sleep(1000);
		log.Title_Name();
		log.Enter_Title_Name("test");
		Thread.sleep(1000);
		log.Schedule_Meeting();
		Thread.sleep(1000);	
		log.Validate_Toast_Msg6();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on later button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Later_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper1);
		ExtentReportManager.logInfo("Enter title name");
		ExtentReportManager.logPass(Validation_CattleCall.Title_Name);
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Title_Name);
		ExtentReportManager.logInfo("Click on schedule button");
		ExtentReportManager.logPass(Validation_CattleCall.Schedule_Meeting);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg6);
	}
	@Test(priority=21)
	public void Schedule_The_Meeting_With_Title_Name_From_Time() throws Exception {
		ExtentReportManager.startTest("Schedule_The_Meeting_With_Title_Name_From_Time", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Later_Button();
		log.Wrapper1();
		Thread.sleep(1000);
		log.Date();
		Thread.sleep(1000);
		log.Select_Date();
		Thread.sleep(1000);
		log.Title_Name();
		log.Enter_Title_Name("test");
		Thread.sleep(1000);
		log.From_Text();
		log.From_Time();
		Thread.sleep(1000);
		log.Select_From_Time_Hours();
		Thread.sleep(1000);
		log.Select_From_Time_In_Minute();
		Thread.sleep(1000);
		log.Schedule_Meeting();
		Thread.sleep(1000);	
		log.Validate_Toast_Msg6();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on later button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Later_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper1);
		ExtentReportManager.logInfo("Enter title name");
		ExtentReportManager.logPass(Validation_CattleCall.Title_Name);
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Title_Name);
		ExtentReportManager.logInfo("Click on schedule button");
		ExtentReportManager.logPass(Validation_CattleCall.Schedule_Meeting);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg6);
	}
	@Test(priority=22)
	public void Schedule_The_Meeting_With_Title_Name_From_And_To_Time() throws Exception {
		ExtentReportManager.startTest("Schedule_The_Meeting_With_Title_Name_From_And_To_Time", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Later_Button();
		log.Wrapper1();
		Thread.sleep(1000);
		log.Date();
		Thread.sleep(1000);
		log.Select_Date();
		Thread.sleep(1000);
		log.Title_Name();
		log.Enter_Title_Name("test");
		Thread.sleep(1000);
		log.From_Text();
		log.From_Time();
		Thread.sleep(1000);
		log.Select_From_Time_Hours();
		Thread.sleep(1000);
		log.Select_From_Time_In_Minute();
		Thread.sleep(1000);
		log.To_Text();
		log.To_Time();
		Thread.sleep(1000);
		log.Select_To_Time_Hours();
		Thread.sleep(1000);
		log.Select_To_Time_In_Minute();
		Thread.sleep(1000);
		log.Schedule_Meeting();
		Thread.sleep(1000);	
		log.Validate_Toast_Msg7();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on later button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Later_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper1);
		ExtentReportManager.logInfo("Enter title name");
		ExtentReportManager.logPass(Validation_CattleCall.Title_Name);
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Title_Name);
		ExtentReportManager.logInfo("Click on schedule button");
		ExtentReportManager.logPass(Validation_CattleCall.Schedule_Meeting);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg7);
	}
	@Test(priority=23)
	public void Enter_Details_And_Add_User() throws Exception {
		ExtentReportManager.startTest("Enter_Details_And_Add_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 4);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Click_On_Later_Button();
		log.Wrapper1();
		Thread.sleep(1000);
		log.Date();
		Thread.sleep(1000);
		log.Select_Date();
		Thread.sleep(1000);
		log.Title_Name();
		log.Enter_Title_Name("test");
		Thread.sleep(1000);
		log.From_Text();
		log.From_Time();
		Thread.sleep(1000);
		log.Select_From_Time_Hours();
		Thread.sleep(1000);
		log.Select_From_Time_In_Minute();
		Thread.sleep(1000);
		log.To_Text();
		log.To_Time();
		Thread.sleep(1000);
		log.Select_To_Time_Hours();
		Thread.sleep(1000);
		log.Select_To_Time_In_Minute();
		Thread.sleep(1000);
		log.Add_Members_Text();
		log.Click_On_Add_Button();
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Click_On_Add_Button1();
		Thread.sleep(1000);
		log.Schedule_Meeting();
		Thread.sleep(1000);	
		log.Validate_Toast_Msg8();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : dummy@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Click on later button");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Later_Button);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper1);
		ExtentReportManager.logInfo("Enter title name");
		ExtentReportManager.logPass(Validation_CattleCall.Title_Name);
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Title_Name);
		ExtentReportManager.logInfo("Click on schedule button");
		ExtentReportManager.logPass(Validation_CattleCall.Schedule_Meeting);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg7);
	}
	@Test(priority=24)
	public void Validate_Today_Meeting() throws Exception {
		ExtentReportManager.startTest("Validate_Today_Meeting", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Today_Meeting();
		log.Today_Meeting1();
		Thread.sleep(2000);		
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the Today's meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting);
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting1);
	}
	@Test(priority=25)
	public void Validate_Join_Meeting() throws Exception {
		ExtentReportManager.startTest("Validate_Join_Meeting", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Join_Meeting();
		Thread.sleep(2000);		
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the Join meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Join_Meeting);
	}
	@Test(priority=26)
	public void Click_On_Submit_Button_Without_Entering_Meeting_ID() throws Exception {
		ExtentReportManager.startTest("Click_On_Submit_Button_Without_Entering_Meeting_ID", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Join_Meeting();
		log.Enter_Meeting_ID("");
		Thread.sleep(1000);
		log.Submit();
		Thread.sleep(100);
		log.Validate_Toast_Msg3();
		Thread.sleep(2000);		
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the Join meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Join_Meeting);
		ExtentReportManager.logInfo("Don't Enter meeting id");
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Meeting_ID);
		ExtentReportManager.logInfo("Click on submit button");
		ExtentReportManager.logPass(Validation_CattleCall.Submit);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg3);
	}
	@Test(priority=27)
	public void Click_On_Submit_Button_With_Entering_Invalid_Meeting_ID() throws Exception {
		ExtentReportManager.startTest("Click_On_Submit_Button_With_Entering_Invalid_Meeting_ID", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Join_Meeting();
		log.Enter_Meeting_ID("231123");
		Thread.sleep(2000);
		log.Submit();
		Thread.sleep(1000);
		Thread.sleep(2000);		
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the Join meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Join_Meeting);
		ExtentReportManager.logInfo("Enter meeting id");
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Meeting_ID);
		ExtentReportManager.logInfo("Click on submit button");
		ExtentReportManager.logPass(Validation_CattleCall.Submit);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg);
	}
	@Test(priority=28)
	public void Click_On_Submit_Button_With_Entering_Valid_Meeting_ID() throws Exception {
		ExtentReportManager.startTest("Click_On_Submit_Button_With_Entering_Valid_Meeting_ID", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Join_Meeting();
		log.Enter_Meeting_ID("77181660");
		Thread.sleep(2000);
		log.Submit();
		Thread.sleep(1000);
		Thread.sleep(2000);		
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the Join meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Join_Meeting);
		ExtentReportManager.logInfo("Enter meeting id");
		ExtentReportManager.logPass(Validation_CattleCall.Enter_Meeting_ID);
		ExtentReportManager.logInfo("Click on submit button");
		ExtentReportManager.logPass(Validation_CattleCall.Submit);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_CattleCall.Validate_Toast_Msg2);
	}
	@Test(priority=29)
	public void Validate_Upcoming_Meeting() throws Exception {
		ExtentReportManager.startTest("Validate_Upcoming_Meeting", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Upcoming_Meeting();
		Thread.sleep(2000);		
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the Upcoming meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Upcoming_Meeting);
	}
	@Test(priority=30)
	public void Upcoming_Meeting() throws Exception {
		ExtentReportManager.startTest("Upcoming_Meeting", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 5);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Upcoming_Meeting1();
		Thread.sleep(2000);	
		log.Dots();
		log.Wrapper3();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the Upcoming meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Upcoming_Meeting1);
		ExtentReportManager.logInfo("Click on 3 dots in upcoming meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Dots);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper3);
	}
	@Test(priority=31)
	public void Click_On_Schedule_Later() throws Exception {
		ExtentReportManager.startTest("Click_On_Schedule_Later", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 5);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Upcoming_Meeting1();
		Thread.sleep(2000);	
		log.Dots();
		log.Wrapper3();
		Thread.sleep(2000);
		log.Schedule_Later();
		Thread.sleep(2000);
		log.Wrapper4();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the Upcoming meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Upcoming_Meeting1);
		ExtentReportManager.logInfo("Click on 3 dots in upcoming meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Dots);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper3);
		ExtentReportManager.logInfo("Click on schedule later");
		ExtentReportManager.logPass(Validation_CattleCall.Schedule_Later);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper4);
	}
	@Test(priority=32)
	public void Click_On_Cancel_Meeting() throws Exception {
		ExtentReportManager.startTest("Click_On_Cancel_Meeting", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 5);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Upcoming_Meeting1();
		Thread.sleep(2000);	
		log.Dots();
		log.Wrapper3();
		Thread.sleep(2000);
		log.Cancel_Meeting1();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the Upcoming meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Upcoming_Meeting1);
		ExtentReportManager.logInfo("Click on 3 dots in upcoming meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Dots);
		ExtentReportManager.logPass(Validation_CattleCall.Wrapper3);
		ExtentReportManager.logInfo("Click on cancel meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Cancel_Meeting1);
	}
	@Test(priority=40)
	public void Click_On_Start_Meeting() throws Exception {
		ExtentReportManager.startTest("Click_On_Start_Meeting", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 2);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Home_Tab();
		log.Conference();
		Thread.sleep(2000);
		log.Today_Meeting2();
		Thread.sleep(2000);
		log.Click_On_Start_Button();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Validate the home page");
		ExtentReportManager.logPass(Validation_CattleCall.Home_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Conference);
		ExtentReportManager.logInfo("Validate the today meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Today_Meeting2);
		ExtentReportManager.logInfo("Click on start meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Start_Button);
	}
	@Test(priority=32)
	public void Click_On_Meeting_Tab() throws Exception {
		ExtentReportManager.startTest("Click_On_Meeting_Tab", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 2);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Meeting_Tab();
		log.Upcoming2();
		Thread.sleep(2000);
		log.Upcoming3();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Click on meeting tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Meeting_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Upcoming2);
		ExtentReportManager.logInfo("Validate the meeting");
		ExtentReportManager.logPass(Validation_CattleCall.Upcoming3);
	}
	@Test(priority=32)
	public void Click_On_Archives_In_Meeting_Tab() throws Exception {
		ExtentReportManager.startTest("Click_On_Archives_In_Meeting_Tab", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Cattlecallpage(driver);
		List<String> info= PropertyReader.getdata("cattlecall", 2);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Cattle_Call();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Meeting_Tab();
		log.Upcoming2();
		Thread.sleep(2000);
		log.Archives();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_CattleCall.Valid_Login);
		ExtentReportManager.logInfo("Click on cattle call tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Cattle_Call);
		ExtentReportManager.logInfo("Click on meeting tab");
		ExtentReportManager.logPass(Validation_CattleCall.Click_On_Meeting_Tab);
		ExtentReportManager.logPass(Validation_CattleCall.Upcoming2);
		ExtentReportManager.logInfo("Click on archives");
		ExtentReportManager.logPass(Validation_CattleCall.Archives);
	}
}
