package TestScript;

import java.util.List;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import Pages.ControlMentionpage;
import Utiles.Browser;
import Utiles.ExtentReportManager;
import Utiles.PropertyReader;
import Validation.Validation_MentionControls;

public class ControlsMention {
	WebDriver driver;
	ControlMentionpage log;
	@BeforeMethod
	public void Setup() throws Exception 
	{
		List<String>info=PropertyReader.getdata("Browser", 1);
		String broswername=info.get(0),drivername=info.get(1),url=info.get(2);
		driver=Browser.Launching_Browser(broswername, drivername);
		driver=Browser.Open_Url(url);
	}

	@AfterMethod
	public void closebroswer()
	{
		driver.close();
		ExtentReportManager.stopReport();
	}
	@Test(priority=1)
	public void Login() throws Exception {
		ExtentReportManager.startTest("Login", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
	}
	@Test(priority=2)
	public void Click_On_Dashboard() throws Exception {
		ExtentReportManager.startTest("Click_On_Dashboard", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
	}
	@Test(priority=3)
	public void Click_On_Controls() throws Exception {
		ExtentReportManager.startTest("Click_On_Controls", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
	}
	@Test(priority=4)
	public void Click_On_Mention_In_Controls() throws Exception {
		ExtentReportManager.startTest("Click_On_Mention_In_Controls", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
	}
	@Test(priority=5)
	public void Disable_Mentions() throws Exception {
		ExtentReportManager.startTest("Disable_Mentions", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Disable_The_Mention();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on disable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Disable_The_Mention);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user or group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
	}
	@Test(priority=6)
	public void Enable_Mentions() throws Exception {
		ExtentReportManager.startTest("Enable_Mentions", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention1();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention1);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user or group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
	}
	@Test(priority=7)
	public void Disable_Mention_In_One_To_One_Chat() throws Exception {
		ExtentReportManager.startTest("Disable_Mention_In_One_To_One_Chat", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label1();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
	}
	@Test(priority=8)
	public void Disable_Mention_In_Group_Chat() throws Exception {
		ExtentReportManager.startTest("Disable_Mention_In_Group_Chat", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label1();
		log.Label2();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("De-Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in group chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label2);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
	}
	@Test(priority=9)
	public void Can_Mention_Non_Group_Users_Within_A_group() throws Exception {
		ExtentReportManager.startTest("Can_Mention_Non_Group_Users_Within_A_group", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label2();
		log.Label3();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group1();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("De-Select the checkbox of disable mention in group chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label2);
		ExtentReportManager.logInfo("Select the checkbox of can mention non group users with a group");
		ExtentReportManager.logPass(Validation_MentionControls.Label3);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group1);
		ExtentReportManager.logInfo("Click on enter Text & Enter user name non group user @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
	}
	@Test(priority=10)
	public void Enter_Minimum_3_characters_after_to_show_mention_users() throws Exception {
		ExtentReportManager.startTest("Enter_Minimum_3_characters_after_to_show_mention_users", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		//log.Enter_MFA("123456");
		//Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label3();
		log.Label4();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		log.Click_On_User1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@b");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group1();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("De-Select the checkbox of can mention non group users with a group");
		ExtentReportManager.logPass(Validation_MentionControls.Label3);
		ExtentReportManager.logInfo("Select the checkbox of Enter minimum 3 characters after @to show mention user");
		ExtentReportManager.logPass(Validation_MentionControls.Label4);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @b");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
	}
	@Test(priority=11)
	public void Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Group_Chat() throws Exception {
		ExtentReportManager.startTest("Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Group_Chat", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label4();
		log.Label1();
		log.Label2();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in group chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label2);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
	}
	@Test(priority=12)
	public void Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Can_Mention_Non_Group_Users() throws Exception {
		ExtentReportManager.startTest("Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Can_Mention_Non_Group_Users", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label2();
		log.Label3();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group1();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("De-Select the checkbox of disable mention in group chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label2);
		ExtentReportManager.logInfo("Select the checkbox of Can mention nn group users within a group");
		ExtentReportManager.logPass(Validation_MentionControls.Label3);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group1);
		ExtentReportManager.logInfo("Click on enter Text & Enter non group user as mention @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
	}
	@Test(priority=13)
	public void Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Enter_Minimum_3_Character() throws Exception {
		ExtentReportManager.startTest("Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Enter_Minimum_3_Character", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label4();
		log.Label3();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_User1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("Select the checkbox of Enter minimum 3 characters after @ to show mention");
		ExtentReportManager.logPass(Validation_MentionControls.Label4);
		ExtentReportManager.logInfo("De-Select the checkbox of Can mention nn group users within a group");
		ExtentReportManager.logPass(Validation_MentionControls.Label3);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
	}
	@Test(priority=14)
	public void Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Group_Chat_And_Enter_Minimum_3_Character() throws Exception {
		ExtentReportManager.startTest("Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Group_Chat_And_Enter_Minimum_3_Character", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label2();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_User1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("Select the checkbox of Enter minimum 3 characters after @ to show mention");
		ExtentReportManager.logPass(Validation_MentionControls.Label4);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in group chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label2);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
	}
	@Test(priority=15)
	public void Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Enter_Minimum_3_Characters_And_Can_Mention_Non_Group_Within_A_Group() throws Exception {
		ExtentReportManager.startTest("Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Enter_Minimum_3_Characters_And_Can_Mention_Non_Group_Within_A_Group", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label2();
		log.Label3();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_User1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("Select the checkbox of Enter minimum 3 characters after @ to show mention");
		ExtentReportManager.logPass(Validation_MentionControls.Label4);
		ExtentReportManager.logInfo("De-Select the checkbox of disable mention in group chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label2);
		ExtentReportManager.logInfo("Select the checkbox of Can mention non group users within a group");
		ExtentReportManager.logPass(Validation_MentionControls.Label3);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
	}
	@Test(priority=16)
	public void Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Group_Chat_And_Can_Mention_Non_Group_Within_A_Group() throws Exception {
		ExtentReportManager.startTest("Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Group_Chat_And_Can_Mention_Non_Group_Within_A_Group", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label2();
		log.Label4();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_User1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("De-Select the checkbox of Enter minimum 3 characters after @ to show mention");
		ExtentReportManager.logPass(Validation_MentionControls.Label4);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in group chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label2);
		ExtentReportManager.logInfo("Select the checkbox of Can mention non group users within a group");
		ExtentReportManager.logPass(Validation_MentionControls.Label3);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
	}
	@Test(priority=17)
	public void Combination_Of_Disable_Mention_In_Group_Chat_And_Can_Mention_Non_Group_Within_A_Group_And_Enter_Minimum_3_Characters() throws Exception {
		ExtentReportManager.startTest("Combination_Of_Disable_Mention_In_Group_Chat_And_Can_Mention_Non_Group_Within_A_Group_And_Enter_Minimum_3_Characters", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label1();
		log.Label4();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Not_Hidden();
		Thread.sleep(2000);
		log.Click_On_User1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("De-Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("Select the checkbox of Enter minimum 3 characters after @ to show mention");
		ExtentReportManager.logPass(Validation_MentionControls.Label4);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in group chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label2);
		ExtentReportManager.logInfo("Select the checkbox of Can mention non group users within a group");
		ExtentReportManager.logPass(Validation_MentionControls.Label3);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Not_Hidden);
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
	}
	@Test(priority=18)
	public void Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Group_Chat_And_Can_Mention_Non_Group_Within_A_Group_And_Enter_Minimum_3_Characters() throws Exception {
		ExtentReportManager.startTest("Combination_Of_Disable_Mention_In_One_To_One_Chat_And_Group_Chat_And_Can_Mention_Non_Group_Within_A_Group_And_Enter_Minimum_3_Characters", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new ControlMentionpage(driver);
		List<String> info= PropertyReader.getdata("groupcontrols", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Dashboard();
		driver.switchTo().frame(0);
		Thread.sleep(2000);
		log.Click_On_Controls();
		Thread.sleep(1000);
		log.Click_On_Mention();
		Thread.sleep(1000);
		log.Validate_Mention_Text();
		log.Validate_Mention();
		Thread.sleep(2000);
		log.Enable_The_Mention();
		Thread.sleep(1000);
		log.Label1();
		Thread.sleep(1000);
		log.Save_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(5000);
		driver.navigate().refresh();
		Thread.sleep(2000);
		log.Click_On_User();
		log.Enter_Mention("@sha");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_User1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group();
		log.Enter_Mention("@bro");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		log.Click_On_Group1();
		log.Enter_Mention("@s");
		Thread.sleep(2000);
		log.Mention_Hidden();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : android@tm.com");
		ExtentReportManager.logInfo("Password : 123456");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_MentionControls.Valid_Login);
		ExtentReportManager.logInfo("Click on dashboard");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Dashboard);
		ExtentReportManager.logInfo("Click on controls");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Controls);
		ExtentReportManager.logInfo("Click on mentions");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Mention);
		ExtentReportManager.logInfo("Validate mention page");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention_Text);
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Mention);
		ExtentReportManager.logInfo("Click on enable radio button");
		ExtentReportManager.logPass(Validation_MentionControls.Enable_The_Mention);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in one to one chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label1);
		ExtentReportManager.logInfo("Select the checkbox of Enter minimum 3 characters after @ to show mention");
		ExtentReportManager.logPass(Validation_MentionControls.Label4);
		ExtentReportManager.logInfo("Select the checkbox of disable mention in group chat");
		ExtentReportManager.logPass(Validation_MentionControls.Label2);
		ExtentReportManager.logInfo("Select the checkbox of Can mention non group users within a group");
		ExtentReportManager.logPass(Validation_MentionControls.Label3);
		ExtentReportManager.logInfo("Click on save button");
		ExtentReportManager.logPass(Validation_MentionControls.Save_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_MentionControls.Validate_Toast_Msg);
		ExtentReportManager.logInfo("Refresh the page");
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User);
		ExtentReportManager.logInfo("Click on enter Text & Enter @sha");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on user");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_User1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group);
		ExtentReportManager.logInfo("Click on enter Text & Enter @bro");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
		ExtentReportManager.logInfo("Click on group");
		ExtentReportManager.logPass(Validation_MentionControls.Click_On_Group1);
		ExtentReportManager.logInfo("Click on enter Text & Enter @s");
		ExtentReportManager.logPass(Validation_MentionControls.Enter_Mention);
		ExtentReportManager.logInfo("Validate the entered mention");
		ExtentReportManager.logPass(Validation_MentionControls.Mention_Hidden);
	}
}
