package TestScript;

import java.util.List;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import Pages.Notifypage;
import Utiles.Browser;
import Utiles.ExtentReportManager;
import Utiles.PropertyReader;
import Validation.Validation_Notify;

public class NotifyTest {
	WebDriver driver;
	Notifypage log;
	@BeforeMethod
	public void Setup() throws Exception 
	{
		List<String>info=PropertyReader.getdata("Browser", 1);
		String broswername=info.get(0),drivername=info.get(1),url=info.get(2);
		driver=Browser.Launching_Browser(broswername, drivername);
		driver=Browser.Open_Url(url);
	}

	@AfterMethod
	public void closebroswer()
	{
		driver.close();
		ExtentReportManager.stopReport();
	}
	@Test(priority=1)
	public void Login() throws Exception {
		ExtentReportManager.startTest("Login", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
	}
	@Test(priority=2)
	public void Click_On_Utilities() throws Exception {
		ExtentReportManager.startTest("Click_On_Utilities", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
	}
	@Test(priority=3)
	public void Empty_Notify_Msgs() throws Exception {
		ExtentReportManager.startTest("Empty_Notify_Msgs", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 2);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(2000);
		log.Invalid_Search();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Validate empty msgs");
		ExtentReportManager.logPass(Validation_Notify.Invalid_Search);
	}
	@Test(priority=4)
	public void Enter_Valid_Search_In_Notify_Msgs() throws Exception {
		ExtentReportManager.startTest("Enter_Valid_Search_In_Notify_Msgs", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(2000);
		log.Enter_Notify_Search("test");
		Thread.sleep(2000);
		log.Valid_Search();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Enter valid search");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Search);
		ExtentReportManager.logPass(Validation_Notify.Valid_Search);
	}
	@Test(priority=5)
	public void Enter_InValid_Search_In_Notify_Msgs() throws Exception {
		ExtentReportManager.startTest("Enter_InValid_Search_In_Notify_Msgs", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(2000);
		log.Enter_Notify_Search("fsaddsf");
		Thread.sleep(2000);
		log.Invalid_Search();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Enter invalid search");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Search);
		ExtentReportManager.logPass(Validation_Notify.Invalid_Search);
	}
	@Test(priority=6)
	public void All_Users_In_Notify() throws Exception {
		ExtentReportManager.startTest("All_Users_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(2000);
		log.Notify_AllUsers();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on all users in notify");
		ExtentReportManager.logPass(Validation_Notify.Notify_AllUsers);
	}
	@Test(priority=7)
	public void Priority_In_Notify() throws Exception {
		ExtentReportManager.startTest("Priority_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(2000);
		log.Notify_Priority();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on priority in notify");
		ExtentReportManager.logPass(Validation_Notify.Notify_Priority);
	}
	@Test(priority=8)
	public void Set_Regular_In_Notify() throws Exception {
		ExtentReportManager.startTest("Set_Regular_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Notify_Priority();
		Thread.sleep(2000);
		log.Notify_Regular();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on priority in notify");
		ExtentReportManager.logPass(Validation_Notify.Notify_Priority);
		ExtentReportManager.logInfo("Click on Regular in priority");
		ExtentReportManager.logPass(Validation_Notify.Notify_Regular);
	}
	@Test(priority=9)
	public void Set_Time_Sensitive_In_Notify() throws Exception {
		ExtentReportManager.startTest("Set_Time_Sensitive_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Notify_Priority();
		Thread.sleep(2000);
		log.Notify_TimeSensitive();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on priority in notify");
		ExtentReportManager.logPass(Validation_Notify.Notify_Priority);
		ExtentReportManager.logInfo("Click on Time Sensitive in priority");
		ExtentReportManager.logPass(Validation_Notify.Notify_TimeSensitive);
	}
	@Test(priority=10)
	public void Set_Urgent_In_Notify() throws Exception {
		ExtentReportManager.startTest("Set_Urgent_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Notify_Priority();
		Thread.sleep(2000);
		log.Notify_Urgent();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on priority in notify");
		ExtentReportManager.logPass(Validation_Notify.Notify_Priority);
		ExtentReportManager.logInfo("Click on Urgent in priority");
		ExtentReportManager.logPass(Validation_Notify.Notify_Urgent);
	}
	@Test(priority=11)
	public void Set_SOS_In_Notify() throws Exception {
		ExtentReportManager.startTest("Set_SOS_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Notify_Priority();
		Thread.sleep(2000);
		log.Notify_SOS();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on priority in notify");
		ExtentReportManager.logPass(Validation_Notify.Notify_Priority);
		ExtentReportManager.logInfo("Click on SOS in priority");
		ExtentReportManager.logPass(Validation_Notify.Notify_SOS);
	}
	@Test(priority=12)
	public void Click_On_Create_New_In_Notify() throws Exception {
		ExtentReportManager.startTest("Click_On_Create_New_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
	}
	@Test(priority=13)
	public void Click_On_Send_Button_Without_Entering_Msg_In_Notify() throws Exception {
		ExtentReportManager.startTest("Click_On_Send_Button_Without_Entering_Msg_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(2000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Validate_Toast_Msg1();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Click on send button");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg1);
	}
	@Test(priority=14)
	public void Click_On_Send_Button_With_Entering_Msg_In_Notify() throws Exception {
		ExtentReportManager.startTest("Click_On_Send_Button_With_Entering_Msg_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Validate_Toast_Msg();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Click on send button");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg);
	}
	@Test(priority=15)
	public void Search_Valid_User_In_Notify() throws Exception {
		ExtentReportManager.startTest("Search_Valid_User_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Search_User("browser");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter Valid user name in create new page");
		ExtentReportManager.logPass(Validation_Notify.Search_User);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
	}
	@Test(priority=16)
	public void Search_InValid_User_In_Notify() throws Exception {
		ExtentReportManager.startTest("Search_InValid_User_In_Notify", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Search_User("sdfasf");
		Thread.sleep(1000);
		log.Search_Invalid_User();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter invalid user name in create new page");
		ExtentReportManager.logPass(Validation_Notify.Search_User);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_Notify.Search_Invalid_User);
	}
	@Test(priority=17)
	public void Validate_Users_Count() throws Exception {
		ExtentReportManager.startTest("Validate_Users_Count", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Validate_User_Count();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Validate the user count");
		ExtentReportManager.logPass(Validation_Notify.Validate_User_Count);
	}
	@Test(priority=18)
	public void Validate_Groups_Count() throws Exception {
		ExtentReportManager.startTest("Validate_Groups_Count", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Validate_Group_Count();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Click on group switch button");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Validate the group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Group_Count);
	}
	@Test(priority=19)
	public void Validate_Selected_Users_Groups_Count() throws Exception {
		ExtentReportManager.startTest("Validate_Selected_Users_Groups_Count", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count);
	}
	@Test(priority=20)
	public void Send_The_Notify_Msg_To_User() throws Exception {
		ExtentReportManager.startTest("Send_The_Notify_Msg_To_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Validate_Selected_User_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count1();
		Thread.sleep(2000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
		ExtentReportManager.logInfo("Validate Selected user count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_User_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count1);
		ExtentReportManager.logInfo("Click on send button");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg2);
	}
	@Test(priority=21)
	public void Send_The_Notify_Msg_To_Group() throws Exception {
		ExtentReportManager.startTest("Send_The_Notify_Msg_To_Group", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Select_Group();
		Thread.sleep(1000);
		log.Validate_Selected_Group_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count1();
		Thread.sleep(2000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Click on Switch button to group");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Select the group");
		ExtentReportManager.logPass(Validation_Notify.Select_Group);
		ExtentReportManager.logInfo("Validate Selected group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Group_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count1);
		ExtentReportManager.logInfo("Click on send button");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg2);
	}
	@Test(priority=22)
	public void Send_The_Notify_Msg_To_User_Group() throws Exception {
		ExtentReportManager.startTest("Send_The_Notify_Msg_To_User_Group", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Select_Group();
		Thread.sleep(1000);
		log.Validate_Selected_User_Group_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count2();
		Thread.sleep(2000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
		ExtentReportManager.logInfo("Click on Switch button to group");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Select the group");
		ExtentReportManager.logPass(Validation_Notify.Select_Group);
		ExtentReportManager.logInfo("Validate Selected group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Group_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count2);
		ExtentReportManager.logInfo("Click on send button");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg2);
	}
	@Test(priority=23)
	public void Search_Valid_User_Or_Group_In_Selected_Members() throws Exception {
		ExtentReportManager.startTest("Search_Valid_User_Or_Group_In_Selected_Members", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Select_Group();
		Thread.sleep(1000);
		log.Validate_Selected_User_Group_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count2();
		Thread.sleep(2000);
		log.Selected_Search("browser");
		Thread.sleep(1000);
		log.Select_User1();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
		ExtentReportManager.logInfo("Click on Switch button to group");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Select the group");
		ExtentReportManager.logPass(Validation_Notify.Select_Group);
		ExtentReportManager.logInfo("Validate Selected group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Group_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count2);
		ExtentReportManager.logInfo("Enter valid search in selected members/groups");
		ExtentReportManager.logPass(Validation_Notify.Selected_Search);
		ExtentReportManager.logInfo("Validated the searched user");
		ExtentReportManager.logPass(Validation_Notify.Select_User1);
	}
	@Test(priority=24)
	public void Search_Invalid_User_Or_Group_In_Selected_Members() throws Exception {
		ExtentReportManager.startTest("Search_Invalid_User_Or_Group_In_Selected_Members", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Select_Group();
		Thread.sleep(1000);
		log.Validate_Selected_User_Group_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count2();
		Thread.sleep(2000);
		log.Selected_Search("sdfasdf");
		Thread.sleep(1000);
		log.Search_Invalid_User();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
		ExtentReportManager.logInfo("Click on Switch button to group");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Select the group");
		ExtentReportManager.logPass(Validation_Notify.Select_Group);
		ExtentReportManager.logInfo("Validate Selected group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Group_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count2);
		ExtentReportManager.logInfo("Enter invalid search in selected members/groups");
		ExtentReportManager.logPass(Validation_Notify.Selected_Search);
		ExtentReportManager.logInfo("Validated the searched");
		ExtentReportManager.logPass(Validation_Notify.Search_Invalid_User);
	}
	@Test(priority=25)
	public void Send_Regular_Notify_Msg() throws Exception {
		ExtentReportManager.startTest("Send_Regular_Notify_Msg", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Select_Group();
		Thread.sleep(1000);
		log.Validate_Selected_User_Group_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count2();
		Thread.sleep(2000);
		log.Select_Priority_In_Notify();
		Thread.sleep(1000);
		log.Validate_Priority_In_Notify();
		Thread.sleep(1000);
		log.Send_Priority_With_Regular_In_Notify();
		Thread.sleep(1000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
		ExtentReportManager.logInfo("Click on Switch button to group");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Select the group");
		ExtentReportManager.logPass(Validation_Notify.Select_Group);
		ExtentReportManager.logInfo("Validate Selected group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Group_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count2);
		ExtentReportManager.logInfo("Click on priority");
		ExtentReportManager.logPass(Validation_Notify.Select_Priority_In_Notify);
		ExtentReportManager.logInfo("Validated the priority");
		ExtentReportManager.logPass(Validation_Notify.Validate_Priority_In_Notify);
		ExtentReportManager.logInfo("Click on Regular");
		ExtentReportManager.logPass(Validation_Notify.Send_Priority_With_Regular_In_Notify);
		ExtentReportManager.logInfo("Click on send");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg2);
	}
	@Test(priority=26)
	public void Send_Time_Sensitive_Notify_Msg() throws Exception {
		ExtentReportManager.startTest("Send_Time_Sensitive_Notify_Msg", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Select_Group();
		Thread.sleep(1000);
		log.Validate_Selected_User_Group_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count2();
		Thread.sleep(2000);
		log.Select_Priority_In_Notify();
		Thread.sleep(1000);
		log.Validate_Priority_In_Notify();
		Thread.sleep(1000);
		log.Send_Priority_With_Time_Sensitive_In_Notify();
		Thread.sleep(1000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
		ExtentReportManager.logInfo("Click on Switch button to group");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Select the group");
		ExtentReportManager.logPass(Validation_Notify.Select_Group);
		ExtentReportManager.logInfo("Validate Selected group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Group_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count2);
		ExtentReportManager.logInfo("Click on priority");
		ExtentReportManager.logPass(Validation_Notify.Select_Priority_In_Notify);
		ExtentReportManager.logInfo("Validated the priority");
		ExtentReportManager.logPass(Validation_Notify.Validate_Priority_In_Notify);
		ExtentReportManager.logInfo("Click on Time Sensitive");
		ExtentReportManager.logPass(Validation_Notify.Send_Priority_With_Time_Sensitive_In_Notify);
		ExtentReportManager.logInfo("Click on send");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg2);
	}
	@Test(priority=27)
	public void Send_Urgent_Notify_Msg() throws Exception {
		ExtentReportManager.startTest("Send_Urgent_Notify_Msg", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Select_Group();
		Thread.sleep(1000);
		log.Validate_Selected_User_Group_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count2();
		Thread.sleep(2000);
		log.Select_Priority_In_Notify();
		Thread.sleep(1000);
		log.Validate_Priority_In_Notify();
		Thread.sleep(1000);
		log.Send_Priority_With_Urgent_In_Notify();
		Thread.sleep(1000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
		ExtentReportManager.logInfo("Click on Switch button to group");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Select the group");
		ExtentReportManager.logPass(Validation_Notify.Select_Group);
		ExtentReportManager.logInfo("Validate Selected group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Group_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count2);
		ExtentReportManager.logInfo("Click on priority");
		ExtentReportManager.logPass(Validation_Notify.Select_Priority_In_Notify);
		ExtentReportManager.logInfo("Validated the priority");
		ExtentReportManager.logPass(Validation_Notify.Validate_Priority_In_Notify);
		ExtentReportManager.logInfo("Click on Urgent");
		ExtentReportManager.logPass(Validation_Notify.Send_Priority_With_Urgent_In_Notify);
		ExtentReportManager.logInfo("Click on send");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg2);
	}
	@Test(priority=28)
	public void Send_SOS_Notify_Msg_With_Confirmation_Text_No_Button() throws Exception {
		ExtentReportManager.startTest("Send_SOS_Notify_Msg_With_Confirmation_Text_No_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Select_Group();
		Thread.sleep(1000);
		log.Validate_Selected_User_Group_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count2();
		Thread.sleep(2000);
		log.Select_Priority_In_Notify();
		Thread.sleep(1000);
		log.Validate_Priority_In_Notify();
		Thread.sleep(1000);
		log.Send_Priority_With_SOS_In_Notify();
		Thread.sleep(1000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Confirmation_Text_Of_SOS();
		Thread.sleep(1000);
		log.No_Button();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
		ExtentReportManager.logInfo("Click on Switch button to group");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Select the group");
		ExtentReportManager.logPass(Validation_Notify.Select_Group);
		ExtentReportManager.logInfo("Validate Selected group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Group_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count2);
		ExtentReportManager.logInfo("Click on priority");
		ExtentReportManager.logPass(Validation_Notify.Select_Priority_In_Notify);
		ExtentReportManager.logInfo("Validated the priority");
		ExtentReportManager.logPass(Validation_Notify.Validate_Priority_In_Notify);
		ExtentReportManager.logInfo("Click on SOS");
		ExtentReportManager.logPass(Validation_Notify.Send_Priority_With_SOS_In_Notify);
		ExtentReportManager.logInfo("Click on send");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate the confirmation text of SOS");
		ExtentReportManager.logPass(Validation_Notify.Confirmation_Text_Of_SOS);
		ExtentReportManager.logInfo("Click on no button");
		ExtentReportManager.logPass(Validation_Notify.No_Button);
	}
	@Test(priority=29)
	public void Send_SOS_Notify_Msg_With_Confirmation_Text_Yes_Button() throws Exception {
		ExtentReportManager.startTest("Send_SOS_Notify_Msg_With_Confirmation_Text_Yes_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(1000);
		log.Create_New();
		Thread.sleep(1000);
		log.Create_New_Text();
		Thread.sleep(1000);
		log.Enter_Notify_Msg("test");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(1000);
		log.Switch_Group();
		Thread.sleep(1000);
		log.Select_Group();
		Thread.sleep(1000);
		log.Validate_Selected_User_Group_Count();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups();
		Thread.sleep(1000);
		log.Validate_Selected_Users_Groups_Count2();
		Thread.sleep(2000);
		log.Select_Priority_In_Notify();
		Thread.sleep(1000);
		log.Validate_Priority_In_Notify();
		Thread.sleep(1000);
		log.Send_Priority_With_SOS_In_Notify();
		Thread.sleep(1000);
		log.Click_On_Send();
		Thread.sleep(1000);
		log.Confirmation_Text_Of_SOS();
		Thread.sleep(1000);
		log.Yes_Button();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Click on create new");
		ExtentReportManager.logPass(Validation_Notify.Create_New);
		ExtentReportManager.logInfo("Validate the create new page");
		ExtentReportManager.logPass(Validation_Notify.Create_New_Text);
		ExtentReportManager.logInfo("Enter notify msg");
		ExtentReportManager.logPass(Validation_Notify.Enter_Notify_Msg);
		ExtentReportManager.logInfo("Select the user");
		ExtentReportManager.logPass(Validation_Notify.Select_User);
		ExtentReportManager.logInfo("Click on Switch button to group");
		ExtentReportManager.logPass(Validation_Notify.Switch_Group);
		ExtentReportManager.logInfo("Select the group");
		ExtentReportManager.logPass(Validation_Notify.Select_Group);
		ExtentReportManager.logInfo("Validate Selected group count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Group_Count);
		ExtentReportManager.logInfo("Validate the name of selected users & groups");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups);
		ExtentReportManager.logInfo("Validate the selected users & groups count");
		ExtentReportManager.logPass(Validation_Notify.Validate_Selected_Users_Groups_Count2);
		ExtentReportManager.logInfo("Click on priority");
		ExtentReportManager.logPass(Validation_Notify.Select_Priority_In_Notify);
		ExtentReportManager.logInfo("Validated the priority");
		ExtentReportManager.logPass(Validation_Notify.Validate_Priority_In_Notify);
		ExtentReportManager.logInfo("Click on SOS");
		ExtentReportManager.logPass(Validation_Notify.Send_Priority_With_SOS_In_Notify);
		ExtentReportManager.logInfo("Click on send");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Send);
		ExtentReportManager.logInfo("Validate the confirmation text of SOS");
		ExtentReportManager.logPass(Validation_Notify.Confirmation_Text_Of_SOS);
		ExtentReportManager.logInfo("Click on yes button");
		ExtentReportManager.logPass(Validation_Notify.Yes_Button);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg2);
	}
	@Test(priority=30)
	public void Recall_Notify_Msg() throws Exception {
		ExtentReportManager.startTest("Recall_Notify_Msg", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new Notifypage(driver);
		List<String> info= PropertyReader.getdata("notify", 3);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("123456");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_Utilities();
		Thread.sleep(4000);
		driver.switchTo().frame(0);
		log.Notify_Active();
		Thread.sleep(2000);
		log.Message();
		Thread.sleep(1000);
		log.Validate_Toast_Msg3();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : email@tm.com");
		ExtentReportManager.logInfo("Password : sai@123");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_Notify.Valid_Login);
		ExtentReportManager.logInfo("Click on Utilities");
		ExtentReportManager.logPass(Validation_Notify.Click_On_Utilities);
		ExtentReportManager.logInfo("Validate notify tab");
		ExtentReportManager.logPass(Validation_Notify.Notify_Active);
		ExtentReportManager.logInfo("Select the msg");
		ExtentReportManager.logPass(Validation_Notify.Message);
		ExtentReportManager.logInfo("Recall the selected msg");
		ExtentReportManager.logPass(Validation_Notify.Recall);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_Notify.Validate_Toast_Msg3);
	}
}
