package TestScript;

import java.util.List;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import Pages.TMmonitorpage;
import Utiles.Browser;
import Utiles.ExtentReportManager;
import Utiles.PropertyReader;
import Validation.Validation_TMmonitor;

public class TMmonitorTest {
	WebDriver driver;
	TMmonitorpage log;
	@BeforeMethod
	public void Setup() throws Exception 
	{
		List<String>info=PropertyReader.getdata("Browser", 1);
		String broswername=info.get(0),drivername=info.get(1),url=info.get(2);
		driver=Browser.Launching_Browser(broswername, drivername);
		driver=Browser.Open_Url(url);
	}

	@AfterMethod
	public void closebroswer()
	{
		driver.close();
		ExtentReportManager.stopReport();
	}
	@Test(priority=1)
	public void Login() throws Exception {
		ExtentReportManager.startTest("Login", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
	}
	@Test(priority=2)
	public void Click_On_TM_Monitor() throws Exception {
		ExtentReportManager.startTest("Click_On_TM_Monitor", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
	}
	@Test(priority=3)
	public void Validate_TM_Monitor() throws Exception {
		ExtentReportManager.startTest("Validate_TM_Monitor", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		driver.switchTo().frame(0);
		log.Validate_TM_Monitor();
		Thread.sleep(1000);
		log.Validate_TM_Monitor1();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
		ExtentReportManager.logInfo("Validate TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor1);
	}
	@Test(priority=4)
	public void Click_On_Next_Button_Without_Entering_Password() throws Exception {
		ExtentReportManager.startTest("Click_On_Next_Button_Without_Entering_Password", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		driver.switchTo().frame(0);
		log.Validate_TM_Monitor();
		Thread.sleep(1000);
		log.Validate_TM_Monitor1();
		Thread.sleep(1000);
		log.Enter_Password("");
		log.Click_On_Next();
		Thread.sleep(500);
		log.Validate_Toast_Msg();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
		ExtentReportManager.logInfo("Validate TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor1);
		ExtentReportManager.logInfo("Without entering the password");
		ExtentReportManager.logPass(Validation_TMmonitor.Enter_Password);
		ExtentReportManager.logInfo("Click on Next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Next);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_Toast_Msg);
	}
	@Test(priority=5)
	public void Click_On_Next_Button_With_Entering_Wrong_Password() throws Exception {
		ExtentReportManager.startTest("Click_On_Next_Button_With_Entering_Wrong_Password", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		driver.switchTo().frame(0);
		log.Validate_TM_Monitor();
		Thread.sleep(1000);
		log.Validate_TM_Monitor1();
		Thread.sleep(1000);
		log.Enter_Password("123456");
		Thread.sleep(1000);
		log.Click_On_Next();
		Thread.sleep(1000);
		log.Validate_Toast_Msg1();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
		ExtentReportManager.logInfo("Validate TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor1);
		ExtentReportManager.logInfo("Entering the password : 123456");
		ExtentReportManager.logPass(Validation_TMmonitor.Enter_Password);
		ExtentReportManager.logInfo("Click on Next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Next);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_Toast_Msg1);
	}
	@Test(priority=6)
	public void Click_On_Next_Button_With_Entering_Password() throws Exception {
		ExtentReportManager.startTest("Click_On_Next_Button_With_Entering_Password", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		driver.switchTo().frame(0);
		log.Validate_TM_Monitor();
		Thread.sleep(1000);
		log.Validate_TM_Monitor1();
		Thread.sleep(1000);
		log.Enter_Password("654321");
		Thread.sleep(1000);
		log.Click_On_Next();
		Thread.sleep(1000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
		ExtentReportManager.logInfo("Validate TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor1);
		ExtentReportManager.logInfo("Entering the password : 654321");
		ExtentReportManager.logPass(Validation_TMmonitor.Enter_Password);
		ExtentReportManager.logInfo("Click on Next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Next);
	}
	@Test(priority=7)
	public void Validate_TM_Monitor_Second_Page() throws Exception {
		ExtentReportManager.startTest("Validate_TM_Monitor_Second_Page", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		driver.switchTo().frame(0);
		log.Validate_TM_Monitor();
		Thread.sleep(1000);
		log.Validate_TM_Monitor1();
		Thread.sleep(1000);
		log.Enter_Password("654321");
		Thread.sleep(1000);
		log.Click_On_Next();
		Thread.sleep(1000);
		log.Validate_TM_Monitor2();
		log.Validate_TM_Monitor3();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
		ExtentReportManager.logInfo("Validate TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor1);
		ExtentReportManager.logInfo("Entering the password : 654321");
		ExtentReportManager.logPass(Validation_TMmonitor.Enter_Password);
		ExtentReportManager.logInfo("Click on Next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Next);
		ExtentReportManager.logInfo("Validate the TM-monitor 2nd page");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor2);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor3);
	}
	@Test(priority=8)
	public void Click_On_Next_In_Second_Page_Without_Selecting_User() throws Exception {
		ExtentReportManager.startTest("Click_On_Next_In_Second_Page_Without_Selecting_User", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		driver.switchTo().frame(0);
		log.Validate_TM_Monitor();
		Thread.sleep(1000);
		log.Validate_TM_Monitor1();
		Thread.sleep(1000);
		log.Enter_Password("654321");
		Thread.sleep(1000);
		log.Click_On_Next();
		Thread.sleep(1000);
		log.Validate_TM_Monitor2();
		log.Validate_TM_Monitor3();
		Thread.sleep(2000);
		log.Employee_Name();
		Thread.sleep(1000);
		log.Click_On_Second_Next();
		Thread.sleep(1000);
		log.Validate_Toast_Msg2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
		ExtentReportManager.logInfo("Validate TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor1);
		ExtentReportManager.logInfo("Entering the password : 654321");
		ExtentReportManager.logPass(Validation_TMmonitor.Enter_Password);
		ExtentReportManager.logInfo("Click on Next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Next);
		ExtentReportManager.logInfo("Validate the TM-monitor 2nd page");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor2);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor3);
		ExtentReportManager.logInfo("Don't enter employee name & Click on next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Employee_Name);
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Second_Next);
		ExtentReportManager.logInfo("Validate the toast msg");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_Toast_Msg2);
	}
	@Test(priority=9)
	public void Enter_Valid_Employee_Name() throws Exception {
		ExtentReportManager.startTest("Enter_Valid_Employee_Name", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		driver.switchTo().frame(0);
		log.Validate_TM_Monitor();
		Thread.sleep(1000);
		log.Validate_TM_Monitor1();
		Thread.sleep(1000);
		log.Enter_Password("654321");
		Thread.sleep(1000);
		log.Click_On_Next();
		Thread.sleep(1000);
		log.Validate_TM_Monitor2();
		log.Validate_TM_Monitor3();
		Thread.sleep(2000);
		log.Search_Employee_Name("browser");
		Thread.sleep(1000);
		log.Select_User();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
		ExtentReportManager.logInfo("Validate TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor1);
		ExtentReportManager.logInfo("Entering the password : 654321");
		ExtentReportManager.logPass(Validation_TMmonitor.Enter_Password);
		ExtentReportManager.logInfo("Click on Next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Next);
		ExtentReportManager.logInfo("Validate the TM-monitor 2nd page");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor2);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor3);
		ExtentReportManager.logInfo("Enter employee name : Browser");
		ExtentReportManager.logPass(Validation_TMmonitor.Employee_Name);
		ExtentReportManager.logPass(Validation_TMmonitor.Select_User);
	}
	@Test(priority=10)
	public void Click_On_Any_Employee_Name_With_Next_Button() throws Exception {
		ExtentReportManager.startTest("Click_On_Any_Employee_Name_With_Next_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		driver.switchTo().frame(0);
		log.Validate_TM_Monitor();
		Thread.sleep(1000);
		log.Validate_TM_Monitor1();
		Thread.sleep(1000);
		log.Enter_Password("654321");
		Thread.sleep(1000);
		log.Click_On_Next();
		Thread.sleep(1000);
		log.Validate_TM_Monitor2();
		log.Validate_TM_Monitor3();
		Thread.sleep(2000);
		log.Click_On_Employee_Name();
		Thread.sleep(1000);
		log.Select_User1();
		Thread.sleep(1000);
		log.Click_On_Second_Next();
		Thread.sleep(3000);
		log.Access();
		log.Access1();
		log.Access4();
		log.Access3();
		log.Access2();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
		ExtentReportManager.logInfo("Validate TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor1);
		ExtentReportManager.logInfo("Entering the password : 654321");
		ExtentReportManager.logPass(Validation_TMmonitor.Enter_Password);
		ExtentReportManager.logInfo("Click on Next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Next);
		ExtentReportManager.logInfo("Validate the TM-monitor 2nd page");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor2);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor3);
		ExtentReportManager.logInfo("Click on employee name dropdown");
		ExtentReportManager.logPass(Validation_TMmonitor.Employee_Name);
		ExtentReportManager.logInfo("Select the employee");
		ExtentReportManager.logPass(Validation_TMmonitor.Select_User1);
		ExtentReportManager.logInfo("Click on next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Second_Next);
		ExtentReportManager.logInfo("Validate the user chat");
		ExtentReportManager.logPass(Validation_TMmonitor.Access);
		ExtentReportManager.logPass(Validation_TMmonitor.Access1);
		ExtentReportManager.logPass(Validation_TMmonitor.Access4);
		ExtentReportManager.logPass(Validation_TMmonitor.Access3);
		ExtentReportManager.logPass(Validation_TMmonitor.Access2);
	}
	@Test(priority=11)
	public void Click_On_End_Button() throws Exception {
		ExtentReportManager.startTest("Click_On_End_Button", "test case description","test case pass");
		ExtentReportManager.startReport();
		log=new TMmonitorpage(driver);
		List<String> info= PropertyReader.getdata("tmmonitor", 1);
		String Email=info.get(0);
		//String Password=info.get(1);
		log.Click_On_Login_Link();
		Thread.sleep(3000);
		log.Set_Email(Email);
		log.Set_Password("654321");
		Thread.sleep(2000);
		log.Click_On_Login_Btn();
		Thread.sleep(5000);
		log.Validate_Login();
		Thread.sleep(1000);
		log.Click_On_TM_Monitor();
		Thread.sleep(2000);
		driver.switchTo().frame(0);
		log.Validate_TM_Monitor();
		Thread.sleep(1000);
		log.Validate_TM_Monitor1();
		Thread.sleep(1000);
		log.Enter_Password("654321");
		Thread.sleep(1000);
		log.Click_On_Next();
		Thread.sleep(1000);
		log.Validate_TM_Monitor2();
		log.Validate_TM_Monitor3();
		Thread.sleep(2000);
		log.Click_On_Employee_Name();
		Thread.sleep(1000);
		log.Select_User1();
		Thread.sleep(1000);
		log.Click_On_Second_Next();
		Thread.sleep(3000);
		log.Access();
		log.Access1();
		log.Access4();
		log.Access3();
		log.Access2();
		Thread.sleep(2000);
		log.Access5();
		Thread.sleep(3000);
		log.Tm_Monitor();
		Thread.sleep(2000);
		ExtentReportManager.logInfo("Chrome Browser Launched Successfully");
		ExtentReportManager.logInfo("Navigate to URL");
		ExtentReportManager.logInfo("Click on login button in home page");
		ExtentReportManager.logInfo("Email : admin@tm.com");
		ExtentReportManager.logInfo("Password : 654321");
		ExtentReportManager.logInfo("Click on login button");
		ExtentReportManager.logPass(Validation_TMmonitor.Valid_Login);
		ExtentReportManager.logInfo("Click on TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_TM_Monitor);
		ExtentReportManager.logInfo("Validate TM-monitor");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor1);
		ExtentReportManager.logInfo("Entering the password : 654321");
		ExtentReportManager.logPass(Validation_TMmonitor.Enter_Password);
		ExtentReportManager.logInfo("Click on Next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Next);
		ExtentReportManager.logInfo("Validate the TM-monitor 2nd page");
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor2);
		ExtentReportManager.logPass(Validation_TMmonitor.Validate_TM_Monitor3);
		ExtentReportManager.logInfo("Click on employee name dropdown");
		ExtentReportManager.logPass(Validation_TMmonitor.Employee_Name);
		ExtentReportManager.logInfo("Select the employee");
		ExtentReportManager.logPass(Validation_TMmonitor.Select_User1);
		ExtentReportManager.logInfo("Click on next button");
		ExtentReportManager.logPass(Validation_TMmonitor.Click_On_Second_Next);
		ExtentReportManager.logInfo("Validate the user chat");
		ExtentReportManager.logPass(Validation_TMmonitor.Access);
		ExtentReportManager.logPass(Validation_TMmonitor.Access1);
		ExtentReportManager.logPass(Validation_TMmonitor.Access4);
		ExtentReportManager.logPass(Validation_TMmonitor.Access3);
		ExtentReportManager.logPass(Validation_TMmonitor.Access2);
		ExtentReportManager.logInfo("Click on End button");
		ExtentReportManager.logPass(Validation_TMmonitor.Access2);
		ExtentReportManager.logInfo("Validate the page");
		ExtentReportManager.logPass(Validation_TMmonitor.Tm_Monitor);
	}
}
